---
spring:
  profiles: dev #dev,test,prod。此处默认为dev，加加载application-dev.yml中的配置
server:
  port: 8887
  
---
spring:
  profiles: prod #dev,test,prod。此处默认为dev，加加载application-dev.yml中的配置
server:
  port: 8888
  
---
spring:
  profiles: native #从本地文件系统中加载配置, 默认是从git处加载
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/configs/{application}
#          searchLocations: classpath:/configs
server:
  port: 8889