server:
  port: 8888

spring: 
  cloud: 
    config: 
      server: 
        git:
          #从github处加载配置
          uri: https://github.com/dengGQ/springcloud-simple-demo
          search-paths: config-repo
        skipSslValidation: true