#server:
#  port: 8887
#
#spring:
#  profiles:
#    active: native #从本地文件系统中加载配置, 默认是从git处加载
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: classpath:/configs/{application}
##          searchLocations: classpath:/configs